name: dart_lint
version: 0.0.1
author: Dart Team <misc@dartlang.org>
description: Style linter for Dart.
homepage: https://github.com/dart-lang/dart_lint
dependencies:
  analyzer: '0.23.0-dev.16'
  grinder: '>=0.6.0 <0.7.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'